network:
  name: nflow
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'

  # normalizing flow network
  nflow:
    # The size of the latent space
    latent_size: 512
    # Number of flows
    n_flows: 4
    # The clamp value for the MLPs
    clamp_value: 25.0

  # network used for feature extraction
  backbone:
    name: resnet18_28x28
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    checkpoint: none
    checkpoint_key: none
    num_gpus: '@{num_gpus}'
