network:
  name: nflow
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'

  # normalizing flow network (RealNVP)
  nflow:
    latent_size: 512  # The size of the latent space
    hidden_size: 1024  # The number of the hidden units
    n_flows: 4  # Number of flows
    clamp_value: 25.0  # The value used for clamping st_network outputs
    clamp_method: "HARD"  # The clamp method, choices: [HARD, TANH, SIGMOID, ATAN]
    clamp_t: True  # Whether to clamp the t-network outputs as well as s-network outputs
    normalize_input: False  # l2-normalize the input of the nflow network

  # network used for feature extraction
  backbone:
    name: resnet18_224x224
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    checkpoint: none
    checkpoint_key: none
    num_gpus: '@{num_gpus}'
