network:
  name: nflow
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'

  # normalizing flow network (RealNVP)
  nflow:
    latent_size: 2352  # The size of the latent space (28x28x3 for raw images)
    hidden_size: 2048  # The number of the hidden units
    n_flows: 32  # Number of flows
    clamp_value: 1.0  # The value used for clamping st_network outputs
    clamp_method: "ATAN"  # The clamp method, choices: [HARD, TANH, SIGMOID, ATAN]
    clamp_t: False  # Whether to clamp the t-network outputs as well as s-network outputs
    l2_normalize: True  # l2-normalize the input of the nflow network
    arch: "RealNVP" # The architecture of the normalizing flow, choices: [RealNVP, Glow]

  # network used for feature extraction
  backbone:
    name: identity
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    checkpoint: none
    checkpoint_key: none
    num_gpus: '@{num_gpus}'
