exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_'@{mark}'/s'@{seed}'"
output_dir: ./results/
save_output: True
merge_option: default
mark: default
seed: 0

num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0

pipeline:
  name: train_med3d

trainer:
  name: med3d

evaluator:
  name: med3d
  extra_metrics: ['f1', 'precision', 'recall']

optimizer:
  name: adam
  num_epochs: 100
  lr: 0.0001
  betas: [0.5, 0.999]
  weight_decay: 0
# ---------------
#  name: sgd
#  num_epochs: 100
#  lr: 0.1
#  momentum: 0.9
#  weight_decay: 0.0005

recorder:
  name: med3d
  save_all_models: False
  best_metric: 'f1'
  average: 'weighted'

scheduler:
  name: poly
  power: 0.9
# ---------------
#  name: multi-step
#  milestones: [35, 65]
#  gamma: 0.1
# ---------------
#  name: cosine

#loss:
#  name: 'weighted-ce'
#  weight: [0.6, 0.4]
