dataset:
  name: organamnist
  num_classes: 11
  num_channels: 3
  pre_size: 28
  image_size: 28

  interpolation: nearest
  normalization_type: medmnist

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/medmnist/
    imglist_pth: ./data/benchmark_imglist/medmnist/train_organamnist_50p.txt
    batch_size: 128
    shuffle: True
    drop_last: False
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/medmnist/
    imglist_pth: ./data/benchmark_imglist/medmnist/val_organamnist.txt
    batch_size: 200
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/medmnist/
    imglist_pth: ./data/benchmark_imglist/medmnist/test_organamnist.txt
    batch_size: 200
    shuffle: False
