ood_dataset:
  name: organamnist_ood
  num_classes: 11
  num_channels: 3

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False

  split_names: [val, nearood, farood]
  val:
    data_dir: ./data/medmnist/
    imglist_pth: ./data/benchmark_imglist/medmnist/val_organcmnist.txt
  nearood:
    datasets: [organcmnist, organsmnist, chestmnist, pneumoniamnist]
    organcmnist:
      data_dir: ./data/medmnist/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_organcmnist.txt
    organsmnist:
      data_dir: ./data/medmnist/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_organsmnist.txt
    chestmnist:
      data_dir: ./data/medmnist/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_chestmnist.txt
    pneumoniamnist:
      data_dir: ./data/medmnist/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_pneumoniamnist.txt
  farood:
    datasets: [pathmnist, dermamnsit, retinamnist, bloodmnist, mnist, cifar10, texture, tin]
    pathmnist:
      data_dir: ./data/medmnist/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_pathmnist.txt
    dermamnsit:
      data_dir: ./data/medmnist/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_dermamnist.txt
    retinamnist:
      data_dir: ./data/medmnist/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_retinamnist.txt
    bloodmnist:
      data_dir: ./data/medmnist/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_bloodmnist.txt
    mnist:
      data_dir: ./data/images/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_mnist.txt
    cifar10:
      data_dir: ./data/images/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_cifar10.txt
    texture:
      data_dir: ./data/images/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_texture.txt
    tin:
      data_dir: ./data/images/
      imglist_pth: ./data/benchmark_imglist/medmnist/test_tin.txt
