ood_dataset:
  name: organamnist_224_ood
  num_classes: 11
  num_channels: 3

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False

  split_names: [val, nearood, farood]
  val:
    data_dir: ./data/medmnist_plus/
    imglist_pth: ./data/benchmark_imglist/medmnist_plus/val_organcmnist_224.txt
  nearood:
    datasets: [organcmnist, organsmnist, chestmnist, pneumoniamnist]
    organcmnist:
      data_dir: ./data/medmnist_plus/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_organcmnist_224.txt
    organsmnist:
      data_dir: ./data/medmnist_plus/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_organsmnist_224.txt
    chestmnist:
      data_dir: ./data/medmnist_plus/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_chestmnist_224.txt
    pneumoniamnist:
      data_dir: ./data/medmnist_plus/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_pneumoniamnist_224.txt
  farood:
    datasets: [pathmnist, dermamnist, retinamnist, bloodmnist, mnist, cifar10, texture, tin]
    pathmnist:
      data_dir: ./data/medmnist_plus/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_pathmnist_224.txt
    dermamnist:
      data_dir: ./data/medmnist_plus/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_dermamnist_224.txt
    retinamnist:
      data_dir: ./data/medmnist_plus/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_retinamnist_224.txt
    bloodmnist:
      data_dir: ./data/medmnist_plus/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_bloodmnist_224.txt
    mnist:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_mnist.txt
    cifar10:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_cifar10.txt
    texture:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_texture.txt
    tin:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/medmnist_plus/test_tin.txt
