ood_dataset:
  name: brats20_t1_fsood
  num_classes: 2
  num_channels: 1

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: Med3DImglistDataset
  batch_size: 16
  shuffle: False

  split_names: [val, nearood, farood, csid]
  val:
    data_dir: ./data/medood/
    imglist_pth: ./data/benchmark_imglist/medood/val_brats20_t1c.txt
  nearood:
    datasets: [brats20_t1_transformed_motion, brats20_t1_transformed_ghost,
               brats20_t1_transformed_bias, brats20_t1_transformed_spike,
               brats20_t1_transformed_noise, brats20_t1_transformed_downsampling,
               brats20_t1_transformed_scaling, brats20_t1_transformed_gamma,
               brats20_t1_transformed_truncation, brats20_t1_transformed_registration,
               brats23_ped_t1, brats23_ssa_t1]
    brats20_t1_transformed_motion:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1_transformed_motion.txt
    brats20_t1_transformed_ghost:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1_transformed_ghost.txt
    brats20_t1_transformed_bias:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1_transformed_bias.txt
    brats20_t1_transformed_spike:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1_transformed_spike.txt
    brats20_t1_transformed_noise:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1_transformed_noise.txt
    brats20_t1_transformed_downsampling:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1_transformed_downsampling.txt
    brats20_t1_transformed_scaling:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1_transformed_scaling.txt
    brats20_t1_transformed_gamma:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1_transformed_gamma.txt
    brats20_t1_transformed_truncation:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1_transformed_truncation.txt
    brats20_t1_transformed_registration:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1_transformed_registration.txt
    brats23_ped_t1:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats23_ped_t1.txt
    brats23_ssa_t1:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats23_ssa_t1.txt
  farood:
    datasets: [brats20_t1c, brats20_t2f, cq500_ct, ixi_t1, wmh2017_t1, episurg_t1, atlas2_t1, chaos_t1, lumbar_t1]
    brats20_t1c:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1c.txt
    brats20_t2f:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t2f.txt
    cq500_ct:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_cq500_ct.txt
    ixi_t1:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_ixi_t1.txt
    wmh2017_t1:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_wmh2017_t1.txt
    episurg_t1:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_episurg_t1.txt
    atlas2_t1:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_atlas2_t1.txt
    chaos_t1:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_chaos_t1.txt
    lumbar_t1:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_lumbar_t1.txt
  csid:
    datasets: [lumiere_t1]
    lumiere_t1:
      data_dir: ./data/medood/
      imglist_pth: ./data/benchmark_imglist/medood/test_lumiere_t1.txt
