dataset:
  name: brats20_t1
  num_classes: 2
  num_channels: 1
  pre_size: [128, 128, 128]
  image_size: [112, 112, 112]

  processing_type: medood

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: Med3DImglistDataset
    data_dir: ./data/medood/
    imglist_pth: ./data/benchmark_imglist/medood/train_brats20_t1.txt
    batch_size: 8
    shuffle: True
    drop_last: False
  val:
    dataset_class: Med3DImglistDataset
    data_dir: ./data/medood/
    imglist_pth: ./data/benchmark_imglist/medood/val_brats20_t1.txt
    batch_size: 8
    shuffle: False
  test:
    dataset_class: Med3DImglistDataset
    data_dir: ./data/medood/
    imglist_pth: ./data/benchmark_imglist/medood/test_brats20_t1.txt
    batch_size: 8
    shuffle: False
